### ISSUE TITLE
Host the Binaries on Github

### ISSUE THREAD

**Issue by greysondn** [Hawkynt/2dimagefilter#22]
I don't even what are you doing? Host the binaries on github!

**Comment by CodeF53** [comment]
A binary is hosted on the github now, please close the issue.

**Comment by greysondn** [comment]
Releases aren't tabbed. You might consider linking them from the main readme.

<https://github.com/Hawkynt/2dimagefilter/releases>

**Comment by CodeF53** [comment]
I will make a new issue for this and link a fork.
I don't have permissions to make changes to the project itself
